config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 246606 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

models:
  jaffle_shop:
    staging:
      +schema: stg
      +database: "jaffle_shop_{{ env_var('DBT_SNOWFLAKE_ENV') }}"
      +materialized: view
    marts:
      +schema: marts
      +database: "jaffle_shop_{{ env_var('DBT_SNOWFLAKE_ENV') }}"
      +materialized: table
